const commands = [
    { id: 1, command: "ipconfig", description: "Exibe as configurações de IP do sistema." },
    { id: 2, command: "ipconfig /all", description: "Exibe informações detalhadas de configuração de IP." },
    { id: 3, command: "ipconfig /release", description: "Libera o endereço IP atual." },
    { id: 4, command: "ipconfig /renew", description: "Renova o endereço IP." },
    { id: 5, command: "ipconfig /flushdns", description: "Limpa o cache do DNS resolver." },
    { id: 6, command: "ipconfig /registerdns", description: "Atualiza as configurações do DNS e registra o DNS novamente." },
    { id: 7, command: "ping", description: "Testa a conectividade com outro dispositivo de rede." },
    { id: 8, command: "ping -t", description: "Envia pacotes de ping indefinidamente para testar a estabilidade." },
    { id: 9, command: "ping -l", description: "Especifica o tamanho dos pacotes de ping." },
    { id: 10, command: "tracert", description: "Rastreia a rota até um destino de rede." },
    { id: 11, command: "pathping", description: "Combina funcionalidades de ping e tracert para diagnosticar perda de pacotes." },
    { id: 12, command: "netstat", description: "Exibe conexões de rede e estatísticas de portas." },
    { id: 13, command: "netstat -an", description: "Lista todas as conexões ativas e suas portas." },
    { id: 14, command: "netstat -s", description: "Exibe estatísticas detalhadas do protocolo de rede." },
    { id: 15, command: "netsh", description: "Ferramenta avançada para configurar e diagnosticar redes." },
    { id: 16, command: "netsh int ip reset", description: "Restaura o TCP/IP para o estado padrão." },
    { id: 17, command: "netsh winsock reset", description: "Reseta o catálogo do Winsock." },
    { id: 18, command: "netsh advfirewall reset", description: "Reseta as configurações do firewall para o padrão." },
    { id: 19, command: "netsh interface ipv6 reset", description: "Reseta a configuração de IPv6." },
    { id: 20, command: "netsh interface ipv4 reset", description: "Reseta a configuração de IPv4." },
    { id: 21, command: "arp -a", description: "Exibe a tabela ARP de mapeamento IP para MAC." },
    { id: 22, command: "nbtstat -a", description: "Exibe a tabela de nomes NetBIOS em um dispositivo remoto." },
    { id: 23, command: "nbtstat -c", description: "Mostra o cache de nomes NetBIOS." },
    { id: 24, command: "nslookup", description: "Consulta servidores DNS para obter o endereço IP de um nome de domínio." },
    { id: 25, command: "route print", description: "Exibe a tabela de roteamento do IP." },
    { id: 26, command: "route add", description: "Adiciona uma nova rota à tabela de roteamento." },
    { id: 27, command: "route delete", description: "Remove uma rota da tabela de roteamento." },
    { id: 28, command: "telnet", description: "Testa conectividade com um servidor em uma porta específica." },
    { id: 29, command: "getmac", description: "Exibe o endereço MAC de todos os adaptadores de rede." },
    { id: 30, command: "net use", description: "Conecta ou desconecta uma unidade de rede compartilhada." },
    { id: 31, command: "net user", description: "Gerencia contas de usuário no Windows." },
    { id: 32, command: "net localgroup", description: "Gerencia grupos locais de usuários." },
    { id: 33, command: "net share", description: "Gerencia compartilhamentos de rede." },
    { id: 34, command: "net start", description: "Inicia um serviço de rede." },
    { id: 35, command: "net stop", description: "Para um serviço de rede." },
    { id: 36, command: "net config", description: "Exibe informações sobre a configuração de serviços e sistemas." },
    { id: 37, command: "net view", description: "Exibe recursos compartilhados em um computador ou rede." },
    { id: 38, command: "net session", description: "Exibe ou desconecta sessões de usuários." },
    { id: 39, command: "net time", description: "Exibe ou sincroniza o tempo com outro computador ou servidor." },
    { id: 40, command: "net accounts", description: "Atualiza a base de dados de contas de usuário e exibe políticas de senhas." },
    { id: 41, command: "powershell -Command Get-NetAdapter", description: "Exibe detalhes sobre os adaptadores de rede." },
    { id: 42, command: "powershell -Command Restart-NetAdapter", description: "Reinicia um adaptador de rede." },
    { id: 43, command: "powershell -Command Get-NetIPConfiguration", description: "Exibe a configuração de IP para adaptadores de rede." },
    { id: 44, command: "powershell -Command Get-NetConnectionProfile", description: "Exibe o perfil de conexão de rede." },
    { id: 45, command: "powershell -Command Set-NetConnectionProfile", description: "Define o perfil de conexão de rede como Público ou Privado." },
    { id: 46, command: "powershell -Command Get-DnsClientServerAddress", description: "Exibe os endereços de servidor DNS configurados." },
    { id: 47, command: "powershell -Command Set-DnsClientServerAddress", description: "Define os endereços de servidor DNS para um adaptador de rede." },
    { id: 48, command: "powershell -Command Get-NetFirewallProfile", description: "Exibe os perfis de firewall configurados." },
    { id: 49, command: "powershell -Command Set-NetFirewallProfile", description: "Configura as políticas de perfil de firewall." },
    { id: 50, command: "powershell -Command New-NetIPAddress", description: "Configura manualmente um novo endereço IP." },
    { id: 51, command: "powershell -Command Remove-NetIPAddress", description: "Remove um endereço IP configurado manualmente." },
    { id: 52, command: "powershell -Command Test-NetConnection", description: "Verifica a conectividade de rede, como ping e portas." },
    { id: 53, command: "powershell -Command Resolve-DnsName", description: "Resolve um nome de domínio para um endereço IP usando DNS." },
    { id: 54, command: "netcfg -d", description: "Remove todas as configurações de rede e reinicia o sistema." },
    { id: 55, command: "sc config", description: "Configura os serviços de rede." },
    { id: 56, command: "sc qc", description: "Consulta a configuração de um serviço." },
    { id: 57, command: "sc query", description: "Exibe o status dos serviços." },
    { id: 58, command: "sc start", description: "Inicia um serviço." },
    { id: 59, command: "sc stop", description: "Para um serviço." },
    { id: 60, command: "netdom query fsmo", description: "Exibe os mestres de operações FSMO no Active Directory." },
    { id: 61, command: "netdom verify", description: "Verifica uma conta de computador no domínio." },
    { id: 62, command: "netdom join", description: "Adiciona um computador ao domínio." },
    { id: 63, command: "netdom remove", description: "Remove um computador do domínio." },
    { id: 64, command: "netsh lan show profiles", description: "Exibe perfis de rede LAN configurados." },
    { id: 65, command: "netsh lan set profile", description: "Configura perfis de rede LAN." },
    { id: 66, command: "netsh wlan show profiles", description: "Exibe perfis de rede Wi-Fi configurados." },
    { id: 67, command: "netsh wlan delete profile", description: "Remove um perfil de rede Wi-Fi configurado." },
    { id: 68, command: "netsh wlan set profileparameter", description: "Configura parâmetros específicos para um perfil de rede Wi-Fi." },
    { id: 69, command: "netsh interface show interface", description: "Exibe as interfaces de rede." },
    { id: 70, command: "netsh interface ipv4 set address", description: "Configura o endereço IPv4 para uma interface de rede." },
    { id: 71, command: "netsh interface ipv6 set address", description: "Configura o endereço IPv6 para uma interface de rede." },
    { id: 72, command: "netsh interface ipv4 set dns", description: "Configura o servidor DNS IPv4 para uma interface de rede." },
    { id: 73, command: "netsh interface ipv6 set dns", description: "Configura o servidor DNS IPv6 para uma interface de rede." },
    { id: 74, command: "netsh interface ipv4 show config", description: "Exibe a configuração IPv4 de uma interface de rede." },
    { id: 75, command: "netsh interface ipv6 show config", description: "Exibe a configuração IPv6 de uma interface de rede." },
    { id: 76, command: "netsh http show sslcert", description: "Exibe certificados SSL vinculados a portas HTTP." },
    { id: 77, command: "netsh http add sslcert", description: "Adiciona um certificado SSL a uma porta HTTP." },
    { id: 78, command: "netsh http delete sslcert", description: "Remove um certificado SSL de uma porta HTTP." },
    { id: 79, command: "netsh http show iplisten", description: "Exibe endereços IP que escutam portas HTTP." },
    { id: 80, command: "netsh http add iplisten", description: "Adiciona um endereço IP para escutar portas HTTP." },
    { id: 81, command: "netsh http delete iplisten", description: "Remove um endereço IP que escuta portas HTTP." },
    { id: 82, command: "netsh http add urlacl", description: "Adiciona uma reserva de URL a um processo específico." },
    { id: 83, command: "netsh http delete urlacl", description: "Remove uma reserva de URL de um processo específico." },
    { id: 84, command: "netsh http show urlacl", description: "Exibe as reservas de URL atuais." },
    { id: 85, command: "netsh interface portproxy add v4tov4", description: "Adiciona uma regra de proxy de porta IPv4 para IPv4." },
    { id: 86, command: "netsh interface portproxy add v4tov6", description: "Adiciona uma regra de proxy de porta IPv4 para IPv6." },
    { id: 87, command: "netsh interface portproxy add v6tov4", description: "Adiciona uma regra de proxy de porta IPv6 para IPv4." },
    { id: 88, command: "netsh interface portproxy add v6tov6", description: "Adiciona uma regra de proxy de porta IPv6 para IPv6." },
    { id: 89, command: "netsh interface portproxy delete", description: "Remove uma regra de proxy de porta." },
    { id: 90, command: "netsh interface portproxy reset", description: "Reseta todas as regras de proxy de porta." },
    { id: 91, command: "netsh interface portproxy show", description: "Exibe as regras de proxy de porta." },
    { id: 92, command: "netsh winhttp show proxy", description: "Exibe as configurações de proxy do WinHTTP." },
    { id: 93, command: "netsh winhttp set proxy", description: "Configura as configurações de proxy do WinHTTP." },
    { id: 94, command: "netsh winhttp reset proxy", description: "Reseta as configurações de proxy do WinHTTP." },
    { id: 95, command: "netsh interface ip show config", description: "Exibe a configuração de IP de todas as interfaces de rede." },
    { id: 96, command: "netsh interface ip add address", description: "Adiciona um endereço IP a uma interface de rede." },
    { id: 97, command: "netsh interface ip delete address", description: "Remove um endereço IP de uma interface de rede." },
    { id: 98, command: "Get-WmiObject Win32_NetworkAdapter", description: "Exibe informações detalhadas sobre adaptadores de rede." },
    { id: 99, command: "Get-NetTCPConnection", description: "Exibe informações sobre conexões TCP ativas." },
    { id: 100, command: "Test-Connection", description: "Teste a conectividade de rede (equivalente ao ping)." }
];

export default commands;