const categories = [
    { id: 1, name: "Configuração de Rede" },
    { id: 2, name: "Diagnóstico de Rede" },
    { id: 3, name: "Gerenciamento de Serviços" },
    { id: 4, name: "Firewall e Segurança" },
    { id: 5, name: "Informações do Sistema" },
    { id: 6, name: "Gerenciamento de Discos" },
    { id: 7, name: "Scripts e Utilitários" },
];

const commands = [
    { id: 1, command: "ipconfig", description: "Exibe as configurações de IP do sistema.", categoryId: 1 },
    { id: 2, command: "ipconfig /all", description: "Exibe informações detalhadas de configuração de IP.", categoryId: 1 },
    { id: 3, command: "ipconfig /release", description: "Libera o endereço IP atual.", categoryId: 1 },
    { id: 4, command: "ipconfig /renew", description: "Renova o endereço IP.", categoryId: 1 },
    { id: 5, command: "ipconfig /flushdns", description: "Limpa o cache do DNS resolver.", categoryId: 1 },
    { id: 6, command: "ipconfig /registerdns", description: "Atualiza as configurações do DNS e registra o DNS novamente.", categoryId: 1 },
    { id: 7, command: "ping", description: "Testa a conectividade com outro dispositivo de rede.", categoryId: 2 },
    { id: 8, command: "ping -t", description: "Envia pacotes de ping indefinidamente para testar a estabilidade.", categoryId: 2 },
    { id: 9, command: "ping -l", description: "Especifica o tamanho dos pacotes de ping.", categoryId: 2 },
    { id: 10, command: "tracert", description: "Rastreia a rota até um destino de rede.", categoryId: 2 },
    { id: 11, command: "pathping", description: "Combina funcionalidades de ping e tracert para diagnosticar perda de pacotes.", categoryId: 2 },
    { id: 12, command: "netstat", description: "Exibe conexões de rede e estatísticas de portas.", categoryId: 2 },
    { id: 13, command: "netstat -an", description: "Lista todas as conexões ativas e suas portas.", categoryId: 2 },
    { id: 14, command: "netstat -s", description: "Exibe estatísticas detalhadas do protocolo de rede.", categoryId: 2 },
    { id: 15, command: "netsh", description: "Ferramenta avançada para configurar e diagnosticar redes.", categoryId: 2 },
    { id: 16, command: "netsh int ip reset", description: "Restaura o TCP/IP para o estado padrão.", categoryId: 2 },
    { id: 17, command: "netsh winsock reset", description: "Reseta o catálogo do Winsock.", categoryId: 2 },
    { id: 18, command: "netsh advfirewall reset", description: "Reseta as configurações do firewall para o padrão.", categoryId: 4 },
    { id: 19, command: "netsh interface ipv6 reset", description: "Reseta a configuração de IPv6.", categoryId: 1 },
    { id: 20, command: "netsh interface ipv4 reset", description: "Reseta a configuração de IPv4.", categoryId: 1 },
    { id: 21, command: "arp -a", description: "Exibe a tabela ARP de mapeamento IP para MAC.", categoryId: 2 },
    { id: 22, command: "nbtstat -a", description: "Exibe a tabela de nomes NetBIOS em um dispositivo remoto.", categoryId: 2 },
    { id: 23, command: "nbtstat -c", description: "Mostra o cache de nomes NetBIOS.", categoryId: 2 },
    { id: 24, command: "nslookup", description: "Consulta servidores DNS para obter o endereço IP de um nome de domínio.", categoryId: 2 },
    { id: 25, command: "route print", description: "Exibe a tabela de roteamento do IP.", categoryId: 2 },
    { id: 26, command: "route add", description: "Adiciona uma nova rota à tabela de roteamento.", categoryId: 2 },
    { id: 27, command: "route delete", description: "Remove uma rota da tabela de roteamento.", categoryId: 2 },
    { id: 28, command: "telnet", description: "Testa conectividade com um servidor em uma porta específica.", categoryId: 2 },
    { id: 29, command: "getmac", description: "Exibe o endereço MAC de todos os adaptadores de rede.", categoryId: 2 },
    { id: 30, command: "net use", description: "Conecta ou desconecta uma unidade de rede compartilhada.", categoryId: 3 },
    { id: 31, command: "net user", description: "Gerencia contas de usuário no Windows.", categoryId: 3 },
    { id: 32, command: "net localgroup", description: "Gerencia grupos locais de usuários.", categoryId: 3 },
    { id: 33, command: "net share", description: "Gerencia compartilhamentos de rede.", categoryId: 3 },
    { id: 34, command: "net start", description: "Inicia um serviço de rede.", categoryId: 3 },
    { id: 35, command: "net stop", description: "Para um serviço de rede.", categoryId: 3 },
    { id: 36, command: "net config", description: "Exibe informações sobre a configuração de serviços e sistemas.", categoryId: 3 },
    { id: 37, command: "net view", description: "Exibe recursos compartilhados em um computador ou rede.", categoryId: 3 },
    { id: 38, command: "net session", description: "Exibe ou desconecta sessões de usuários.", categoryId: 3 },
    { id: 39, command: "net time", description: "Exibe ou sincroniza o tempo com outro computador ou servidor.", categoryId: 3 },
    { id: 40, command: "net accounts", description: "Atualiza a base de dados de contas de usuário e exibe políticas de senhas.", categoryId: 3 },
    { id: 41, command: "powershell -Command Get-NetAdapter", description: "Exibe detalhes sobre os adaptadores de rede.", categoryId: 1 },
    { id: 42, command: "powershell -Command Restart-NetAdapter", description: "Reinicia um adaptador de rede.", categoryId: 1 },
    { id: 43, command: "powershell -Command Get-NetIPConfiguration", description: "Exibe a configuração de IP para adaptadores de rede.", categoryId: 1 },
    { id: 44, command: "powershell -Command Get-NetConnectionProfile", description: "Exibe o perfil de conexão de rede.", categoryId: 1 },
    { id: 45, command: "powershell -Command Set-NetConnectionProfile", description: "Define o perfil de conexão de rede como Público ou Privado.", categoryId: 1 },
    { id: 46, command: "powershell -Command Get-DnsClientServerAddress", description: "Exibe os endereços de servidor DNS configurados.", categoryId: 1 },
    { id: 47, command: "powershell -Command Set-DnsClientServerAddress", description: "Define os endereços de servidor DNS para um adaptador de rede.", categoryId: 1 },
    { id: 48, command: "powershell -Command Get-NetFirewallProfile", description: "Exibe os perfis de firewall configurados.", categoryId: 4 },
    { id: 49, command: "powershell -Command Set-NetFirewallProfile", description: "Configura as políticas de perfil de firewall.", categoryId: 4 },
    { id: 50, command: "powershell -Command New-NetIPAddress", description: "Configura manualmente um novo endereço IP.", categoryId: 1 },
    { id: 51, command: "powershell -Command Remove-NetIPAddress", description: "Remove um endereço IP configurado manualmente.", categoryId: 1 },
    { id: 52, command: "powershell -Command Test-NetConnection", description: "Verifica a conectividade de rede, como ping e portas.", categoryId: 2 },
    { id: 53, command: "powershell -Command Resolve-DnsName", description: "Resolve um nome de domínio para um endereço IP usando DNS.", categoryId: 2 },
    { id: 54, command: "netcfg -d", description: "Remove todas as configurações de rede e reinicia o serviço.", categoryId: 1 },
    { id: 55, command: "netsh wlan show profiles", description: "Exibe perfis de redes Wi-Fi salvas.", categoryId: 1 },
    { id: 56, command: "netsh wlan show profile name=\"NomePerfil\" key=clear", description: "Exibe a chave de segurança de um perfil Wi-Fi específico.", categoryId: 1 },
    { id: 57, command: "netsh wlan set profile parameter", description: "Configura parâmetros de um perfil Wi-Fi.", categoryId: 1 },
    { id: 58, command: "netsh wlan show hostednetwork", description: "Exibe detalhes sobre uma rede hospedada.", categoryId: 1 },
    { id: 59, command: "netsh wlan start hostednetwork", description: "Inicia uma rede Wi-Fi hospedada.", categoryId: 1 },
    { id: 60, command: "netsh wlan stop hostednetwork", description: "Para uma rede Wi-Fi hospedada.", categoryId: 1 },
    { id: 61, command: "systeminfo", description: "Exibe informações detalhadas sobre o sistema operacional e hardware.", categoryId: 5 },
    { id: 62, command: "tasklist", description: "Exibe a lista de processos em execução.", categoryId: 5 },
    { id: 63, command: "taskkill", description: "Finaliza um processo em execução.", categoryId: 5 },
    { id: 64, command: "chkdsk", description: "Verifica a integridade do sistema de arquivos e corrige erros.", categoryId: 6 },
    { id: 65, command: "sfc /scannow", description: "Verifica e repara arquivos de sistema corrompidos.", categoryId: 6 },
    { id: 66, command: "diskpart", description: "Gerencia discos e partições do sistema.", categoryId: 6 },
    { id: 67, command: "format", description: "Formata um disco ou partição.", categoryId: 6 },
    { id: 68, command: "defrag", description: "Desfragmenta o disco rígido.", categoryId: 6 },
    { id: 69, command: "shutdown", description: "Desliga ou reinicia o computador.", categoryId: 7 },
    { id: 70, command: "restart", description: "Reinicia o computador.", categoryId: 7 },
    { id: 71, command: "exit", description: "Encerra a sessão atual do terminal.", categoryId: 7 },
    { id: 72, command: "help", description: "Exibe uma lista de comandos disponíveis.", categoryId: 7 },
    { id: 73, command: "cls", description: "Limpa a tela do terminal.", categoryId: 7 },
    { id: 74, command: "echo", description: "Exibe mensagens ou ativa/desativa o eco.", categoryId: 7 },
    { id: 75, command: "set", description: "Define variáveis de ambiente.", categoryId: 7 },
    { id: 76, command: "pause", description: "Pausa a execução de um script.", categoryId: 7 },
    { id: 77, command: "rem", description: "Adiciona um comentário em um arquivo de script.", categoryId: 7 },
    { id: 78, command: "for", description: "Executa um comando em um loop para um conjunto de itens.", categoryId: 7 },
    { id: 79, command: "if", description: "Executa comandos condicionais.", categoryId: 7 },
    { id: 80, command: "goto", description: "Pula para um rótulo específico em um arquivo de script.", categoryId: 7 },
    { id: 81, command: "start", description: "Inicia uma nova janela de comando ou programa.", categoryId: 7 },
];

export { commands, categories };
